/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsSlugRouteImport } from './routes/hosts.$slug'
import { Route as HostNewRouteImport } from './routes/host.new'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as HostSlugReportsRouteImport } from './routes/host.$slug.reports'
import { Route as HostSlugInviteRouteImport } from './routes/host.$slug.invite'
import { Route as HostSlugGalleryRouteImport } from './routes/host.$slug.gallery'
import { Route as HostSlugDashboardRouteImport } from './routes/host.$slug.dashboard'
import { Route as HostSlugEventsNewRouteImport } from './routes/host.$slug.events.new'
import { Route as HostSlugCheckinEventIdRouteImport } from './routes/host.$slug.checkin.$eventId'
import { Route as HostSlugEventsIdEditRouteImport } from './routes/host.$slug.events.$id.edit'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsSlugRoute = HostsSlugRouteImport.update({
  id: '/hosts/$slug',
  path: '/hosts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostNewRoute = HostNewRouteImport.update({
  id: '/host/new',
  path: '/host/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugReportsRoute = HostSlugReportsRouteImport.update({
  id: '/host/$slug/reports',
  path: '/host/$slug/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugInviteRoute = HostSlugInviteRouteImport.update({
  id: '/host/$slug/invite',
  path: '/host/$slug/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugGalleryRoute = HostSlugGalleryRouteImport.update({
  id: '/host/$slug/gallery',
  path: '/host/$slug/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugDashboardRoute = HostSlugDashboardRouteImport.update({
  id: '/host/$slug/dashboard',
  path: '/host/$slug/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugEventsNewRoute = HostSlugEventsNewRouteImport.update({
  id: '/host/$slug/events/new',
  path: '/host/$slug/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugCheckinEventIdRoute = HostSlugCheckinEventIdRouteImport.update({
  id: '/host/$slug/checkin/$eventId',
  path: '/host/$slug/checkin/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugEventsIdEditRoute = HostSlugEventsIdEditRouteImport.update({
  id: '/host/$slug/events/$id/edit',
  path: '/host/$slug/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/$id': typeof EventsIdRoute
  '/host/new': typeof HostNewRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/$slug/dashboard': typeof HostSlugDashboardRoute
  '/host/$slug/gallery': typeof HostSlugGalleryRoute
  '/host/$slug/invite': typeof HostSlugInviteRoute
  '/host/$slug/reports': typeof HostSlugReportsRoute
  '/host/$slug/checkin/$eventId': typeof HostSlugCheckinEventIdRoute
  '/host/$slug/events/new': typeof HostSlugEventsNewRoute
  '/host/$slug/events/$id/edit': typeof HostSlugEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/$id': typeof EventsIdRoute
  '/host/new': typeof HostNewRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/$slug/dashboard': typeof HostSlugDashboardRoute
  '/host/$slug/gallery': typeof HostSlugGalleryRoute
  '/host/$slug/invite': typeof HostSlugInviteRoute
  '/host/$slug/reports': typeof HostSlugReportsRoute
  '/host/$slug/checkin/$eventId': typeof HostSlugCheckinEventIdRoute
  '/host/$slug/events/new': typeof HostSlugEventsNewRoute
  '/host/$slug/events/$id/edit': typeof HostSlugEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/$id': typeof EventsIdRoute
  '/host/new': typeof HostNewRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/$slug/dashboard': typeof HostSlugDashboardRoute
  '/host/$slug/gallery': typeof HostSlugGalleryRoute
  '/host/$slug/invite': typeof HostSlugInviteRoute
  '/host/$slug/reports': typeof HostSlugReportsRoute
  '/host/$slug/checkin/$eventId': typeof HostSlugCheckinEventIdRoute
  '/host/$slug/events/new': typeof HostSlugEventsNewRoute
  '/host/$slug/events/$id/edit': typeof HostSlugEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/signup'
    | '/tickets'
    | '/events/$id'
    | '/host/new'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host/$slug/dashboard'
    | '/host/$slug/gallery'
    | '/host/$slug/invite'
    | '/host/$slug/reports'
    | '/host/$slug/checkin/$eventId'
    | '/host/$slug/events/new'
    | '/host/$slug/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/signup'
    | '/tickets'
    | '/events/$id'
    | '/host/new'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host/$slug/dashboard'
    | '/host/$slug/gallery'
    | '/host/$slug/invite'
    | '/host/$slug/reports'
    | '/host/$slug/checkin/$eventId'
    | '/host/$slug/events/new'
    | '/host/$slug/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/signup'
    | '/tickets'
    | '/events/$id'
    | '/host/new'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host/$slug/dashboard'
    | '/host/$slug/gallery'
    | '/host/$slug/invite'
    | '/host/$slug/reports'
    | '/host/$slug/checkin/$eventId'
    | '/host/$slug/events/new'
    | '/host/$slug/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  SignupRoute: typeof SignupRoute
  TicketsRoute: typeof TicketsRoute
  EventsIdRoute: typeof EventsIdRoute
  HostNewRoute: typeof HostNewRoute
  HostsSlugRoute: typeof HostsSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  HostSlugDashboardRoute: typeof HostSlugDashboardRoute
  HostSlugGalleryRoute: typeof HostSlugGalleryRoute
  HostSlugInviteRoute: typeof HostSlugInviteRoute
  HostSlugReportsRoute: typeof HostSlugReportsRoute
  HostSlugCheckinEventIdRoute: typeof HostSlugCheckinEventIdRoute
  HostSlugEventsNewRoute: typeof HostSlugEventsNewRoute
  HostSlugEventsIdEditRoute: typeof HostSlugEventsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$slug': {
      id: '/hosts/$slug'
      path: '/hosts/$slug'
      fullPath: '/hosts/$slug'
      preLoaderRoute: typeof HostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/new': {
      id: '/host/new'
      path: '/host/new'
      fullPath: '/host/new'
      preLoaderRoute: typeof HostNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/reports': {
      id: '/host/$slug/reports'
      path: '/host/$slug/reports'
      fullPath: '/host/$slug/reports'
      preLoaderRoute: typeof HostSlugReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/invite': {
      id: '/host/$slug/invite'
      path: '/host/$slug/invite'
      fullPath: '/host/$slug/invite'
      preLoaderRoute: typeof HostSlugInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/gallery': {
      id: '/host/$slug/gallery'
      path: '/host/$slug/gallery'
      fullPath: '/host/$slug/gallery'
      preLoaderRoute: typeof HostSlugGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/dashboard': {
      id: '/host/$slug/dashboard'
      path: '/host/$slug/dashboard'
      fullPath: '/host/$slug/dashboard'
      preLoaderRoute: typeof HostSlugDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/events/new': {
      id: '/host/$slug/events/new'
      path: '/host/$slug/events/new'
      fullPath: '/host/$slug/events/new'
      preLoaderRoute: typeof HostSlugEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/checkin/$eventId': {
      id: '/host/$slug/checkin/$eventId'
      path: '/host/$slug/checkin/$eventId'
      fullPath: '/host/$slug/checkin/$eventId'
      preLoaderRoute: typeof HostSlugCheckinEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/events/$id/edit': {
      id: '/host/$slug/events/$id/edit'
      path: '/host/$slug/events/$id/edit'
      fullPath: '/host/$slug/events/$id/edit'
      preLoaderRoute: typeof HostSlugEventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  SignupRoute: SignupRoute,
  TicketsRoute: TicketsRoute,
  EventsIdRoute: EventsIdRoute,
  HostNewRoute: HostNewRoute,
  HostsSlugRoute: HostsSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  HostSlugDashboardRoute: HostSlugDashboardRoute,
  HostSlugGalleryRoute: HostSlugGalleryRoute,
  HostSlugInviteRoute: HostSlugInviteRoute,
  HostSlugReportsRoute: HostSlugReportsRoute,
  HostSlugCheckinEventIdRoute: HostSlugCheckinEventIdRoute,
  HostSlugEventsNewRoute: HostSlugEventsNewRoute,
  HostSlugEventsIdEditRoute: HostSlugEventsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
